export const SIGN_ERROR_MESSAGE_RECIPIENT_DECLINED =
  "ESIGN_ERROR_ENVELOPE_ALREADY_DECLINED";

export const EP_COMMON_ERROR_PERSONAL_TEMP_OR_DISPOSABLE_EMAIL =
  "EP_COMMON_ERROR_PERSONAL_TEMP_OR_DISPOSABLE_EMAIL";

export const SIGN_ERROR_DOCUMENT_ALREADY_SIGNED =
  "ESIGN_ERROR_RECIPIENT_DOCUMENT_SIGN_COMPLETED";
