export enum ImageName {
  MAIL_BOX = "MAIL_BOX",
  DOCUMENT_SIGNED = "DOCUMENT_SIGNED",
  DOCUMENT_DECLINED = "DOCUMENT_DECLINED",
  DOCUMENT_ERROR = "DOCUMENT_ERROR",
  DOCUMENT_EXPIRED = "DOCUMENT_EXPIRED",
  DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND",
  DOCUMENT_LINK_EXPIRED = "LINK_EXPIRED",
  PAPER_PLANE = "PAPER_PLANE",
  SKAPP_LOGO = "SKAPP_LOGO",
  ROCKET_NOBG = "ROCKET_NOBG",
  UPGRADE_INVOICE_LOGO = "UPGRADE_INVOICE_LOGO"
}
