export enum DirectoryModalTypes {
  DOWNLOAD_CSV = "DOWNLOAD_CSV",
  UPLOAD_CSV = "UPLOAD_CSV",
  INVITE_MEMBERS = "INVITE_MEMBERS",
  UPLOAD_SUMMARY = "UPLOAD_SUMMARY",
  NONE = "NONE",
  UPLOAD_TYPE_SELECT = "UPLOAD_TYPE_SELECT",
  ADD_NEW_RESOURCE = "ADD_NEW_RESOURCE",
  USER_CREDENTIALS = "USER_CREDENTIALS",
  UNSAVED_CHANGES = "UNSAVED_CHANGES"
}
