export enum LeaveTypeFormTypes {
  ADD = "add",
  EDIT = "edit"
}

export enum LeaveTypeToastEnums {
  ADD_LEAVE_TYPE_SUCCESS = "ADD_LEAVE_TYPE_SUCCESS",
  ADD_LEAVE_TYPE_ERROR = "ADD_LEAVE_TYPE_ERROR",
  EDIT_LEAVE_TYPE_SUCCESS = "EDIT_LEAVE_TYPE_SUCCESS",
  EDIT_LEAVE_TYPE_ERROR = "EDIT_LEAVE_TYPE_ERROR"
}

export enum LeaveDurationTypes {
  HALF_DAY = "HALF_DAY",
  FULL_DAY = "FULL_DAY",
  HALF_AND_FULL_DAY = "HALF_AND_FULL_DAY",
  NONE = "NONE"
}

export enum LeaveTypeModalEnums {
  NONE = "NONE",
  INACTIVATE_LEAVE_TYPE = "INACTIVATE_LEAVE_TYPE",
  ACTIVATE_LEAVE_TYPE = "ACTIVATE_LEAVE_TYPE",
  UNSAVED_CHANGES_MODAL = "UNSAVED_CHANGES_MODAL"
}
