export enum LeaveEntitlementModelTypes {
  DOWNLOAD_CSV = "DOWNLOAD_CSV",
  UPLOAD_CSV = "UPLOAD_CSV",
  OVERRIDE_CONFIRMATION = "OVERRIDE_CONFIRMATION",
  BULK_UPLOAD_SUMMARY = "BULK_UPLOAD_SUMMARY",
  NONE = "NONE"
}

export enum LeaveEntitlementToastEnums {
  BULK_UPLOAD_PARTIAL_SUCCESS = "BULK_UPLOAD_PARTIAL_SUCCESS",
  BULK_UPLOAD_COMPLETE_SUCCESS = "BULK_UPLOAD_COMPLETE_SUCCESS",
  BULK_UPLOAD_ERROR = "BULK_UPLOAD_ERROR"
}
