export enum MyRequestsToastMsgKeyEnums {
  HOLIDAY_EXISTS = "HOLIDAY_EXISTS",
  MULTIPLE_HOLIDAYS_EXIST = "MULTIPLE_HOLIDAYS_EXIST",
  LEAVE_ALREADY_APPLIED = "LEAVE_ALREADY_APPLIED",
  MULTIPLE_LEAVES_ALREADY_APPLIED = "MULTIPLE_LEAVES_ALREADY_APPLIED",
  ONLY_HALF_DAY_LEAVE_ALLOWED = "ONLY_HALF_DAY_LEAVE_ALLOWED",
  APPLY_LEAVE_ERROR = "APPLY_LEAVE_ERROR",
  APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS",
  INSUFFICIENT_BALANCE_ERROR = "INSUFFICIENT_BALANCE_ERROR",
  NO_LEAVE_ENTITLEMENT_ERROR = "NO_LEAVE_ENTITLEMENT_ERROR"
}
