export const ALLOCATION_PER_PAGE = 6;

export const MAX_ALLOWED_UPLOADS = 5;

export const MAX_CUSTOM_LEAVE_ALLOCATION_DAYS_ALLOWED = 360;

export const MIN_CUSTOM_LEAVE_ALLOCATION_DAYS_ALLOWED = 0.5;
