package com.skapp.community.peopleplanner.type;

public enum EEO {

	EXECUTIVE_SENIOR_LEVEL_OFFICIALS_AND_MANAGERS, FIRST_MID_LEVEL_OFFICIALS_AND_MANAGERS, PROFESSIONALS, TECHNICIANS,
	SALES_WORKERS, ADMINISTRATIVE_SUPPORT_WORKERS, CRAFT_WORKERS, OPERATIVES, LABORERS_AND_HELPERS, SERVICE_WORKERS

}
