package com.skapp.community.peopleplanner.type;

public enum Ethnicity {

	AFRICAN, CARIBBEAN, INDIAN, MELANESIAN, AUSTRALASIAN_OR_ABORIGINAL, CHINESE, GUAMANIAN, JAPANESE, KOREAN,
	POLYNESIAN, EUROPEAN_OR_ANGLO_SAXON, OTHER_PACIFIC_ISLANDER, LATIN_AMERICAN, ARABIC, VIETNAMESE, MICRONESIAN,
	DECLINED_TO_RESPOND, OTHER_HISPANIC, US_OR_CANADIAN_INDIAN, OTHER_ASIAN, PUERTO_RICAN, FILIPINO, MEXICAN,
	ALASKAN_NATIVE, CUBAN

}
