export enum CreateDocumentsModalTypes {
  DELETE_DOCUMENT = "DELETE_DOCUMENT",
  PREVIEW_DOCUMENT = "PREVIEW_DOCUMENT",
  ADD_EXTERNAL_USER = "ADD_EXTERNAL_USER",
  DELETE_EXTERNAL_USER = "DELETE_EXTERNAL_USER",
  UNSAVED_CHANGES = "UNSAVED_CHANGES",
  NONE = "NONE"
}
