export enum JobFamilyActionModalEnums {
  ADD_JOB_FAMILY = "ADD_JOB_FAMILY",
  EDIT_JOB_FAMILY = "EDIT_JOB_FAMILY",
  JOB_FAMILY_DELETE_CONFIRMATION = "JOB_FAMILY_DELETE_CONFIRMATION",
  JOB_FAMILY_DELETION_WARNING = "JOB_FAMILY_DELETION_WARNING",
  JOB_TITLE_DELETE_CONFIRMATION = "JOB_TITLE_DELETE_CONFIRMATION",
  JOB_TITLE_DELETION_WARNING = "JOB_TITLE_DELETION_WARNING",
  JOB_TITLE_EDIT_CONFIRMATION = "JOB_TITLE_EDIT_CONFIRMATION",
  JOB_FAMILY_TRANSFER_MEMBERS = "JOB_FAMILY_TRANSFER_MEMBERS",
  JOB_TITLE_TRANSFER_MEMBERS = "JOB_TITLE_TRANSFER_MEMBERS",
  UNSAVED_CHANGES_JOB_FAMILY = "UNSAVED_CHANGES_JOB_FAMILY",
  UNSAVED_CHANGES_JOB_FAMILY_TRANSFER_MEMBERS = "UNSAVED_CHANGES_JOB_FAMILY_TRANSFER_MEMBERS",
  UNSAVED_CHANGED_JOB_TITLE_TRANSFER_MEMBERS = "UNSAVED_CHANGED_JOB_TITLE_TRANSFER_MEMBERS",
  ADD_NEW_JOB_FAMILY = "ADD_NEW_JOB_FAMILY",
  ADD_NEW_JOB_TITLE = "ADD_NEW_JOB_TITLE",
  NONE = "NONE"
}

export enum JobFamilyToastEnums {
  AT_LEAST_ONE_JOB_TITLE = "AT_LEAST_ONE_JOB_TITLE",
  ADD_JOB_FAMILY_SUCCESS = "ADD_JOB_FAMILY_SUCCESS",
  ADD_JOB_FAMILY_ERROR = "ADD_JOB_FAMILY_ERROR",
  EDIT_JOB_FAMILY_SUCCESS = "EDIT_JOB_FAMILY_SUCCESS",
  EDIT_JOB_FAMILY_ERROR = "EDIT_JOB_FAMILY_ERROR",
  DELETE_JOB_FAMILY_SUCCESS = "DELETE_JOB_FAMILY_SUCCESS",
  DELETE_JOB_FAMILY_ERROR = "DELETE_JOB_FAMILY_ERROR",
  EDIT_JOB_TITLE_SUCCESS = "EDIT_JOB_TITLE_SUCCESS",
  EDIT_JOB_TITLE_ERROR = "EDIT_JOB_TITLE_ERROR",
  DELETE_JOB_TITLE_SUCCESS = "DELETE_JOB_TITLE_SUCCESS",
  DELETE_JOB_TITLE_ERROR = "DELETE_JOB_TITLE_ERROR",
  JOB_FAMILY_TRANSFER_MEMBERS_SUCCESS = "JOB_FAMILY_TRANSFER_MEMBERS_SUCCESS",
  JOB_FAMILY_TRANSFER_MEMBERS_ERROR = "JOB_FAMILY_TRANSFER_MEMBERS_ERROR",
  JOB_TITLE_TRANSFER_MEMBERS_SUCCESS = "JOB_TITLE_TRANSFER_MEMBERS_SUCCESS",
  JOB_TITLE_TRANSFER_MEMBERS_ERROR = "JOB_TITLE_TRANSFER_MEMBERS_ERROR"
}
